package cmd

import (
	"encoding/json"
	"fmt"
	"strings"
	"testing"

	"github.com/dcadolph/slop-chop/internal/sanitize"
)

// TestTellsText checks the plain listing covers every kind the default profile sets.
func TestTellsText(t *testing.T) {
	def := sanitize.DefaultProfile()
	stdout, _, err := runCLI(t, []string{"tells"}, "")
	if err != nil {
		t.Fatalf("err = %v, want nil", err)
	}

	tests := []struct {
		WantSub string
	}{{ // Test 0: Character swaps with their count.
		WantSub: fmt.Sprintf("character swaps (%d):", len(def.CharReplace)),
	}, { // Test 1: Stock phrases with their count.
		WantSub: fmt.Sprintf("stock phrases (%d):", len(def.PhraseReplace)),
	}, { // Test 2: Buzzwords with their count.
		WantSub: fmt.Sprintf("buzzwords flagged (%d):", len(def.BlockWords)),
	}, { // Test 3: Patterns with their count.
		WantSub: fmt.Sprintf("patterns flagged (%d):", len(def.FlagPatterns)),
	}, { // Test 4: The em-dash swap is quoted with its replacement.
		WantSub: `"—" => ", "`,
	}, { // Test 5: A deleted phrase shows as dropped.
		WantSub: `"in summary, " => (dropped)`,
	}, { // Test 6: The cleanup switches are reported on.
		WantSub: "semicolon split: on",
	}, { // Test 7: No dialect reads off.
		WantSub: "dialect: off",
	}}
	for testNum, test := range tests {
		t.Run(fmt.Sprintf("test %d", testNum), func(t *testing.T) {
			if !strings.Contains(stdout, test.WantSub) {
				t.Errorf("stdout missing %q", test.WantSub)
			}
		})
	}
}

// TestTellsMarkdown checks the docs page carries every section and the generated
// marker, since CI diffs the committed page against this output.
func TestTellsMarkdown(t *testing.T) {
	def := sanitize.DefaultProfile()
	stdout, _, err := runCLI(t, []string{"tells", "--markdown"}, "")
	if err != nil {
		t.Fatalf("err = %v, want nil", err)
	}

	tests := []struct {
		WantSub string
	}{{ // Test 0: The generated marker leads the file.
		WantSub: `<!-- Generated by "slop-chop tells --markdown".`,
	}, { // Test 1: The page title.
		WantSub: "# The tells",
	}, { // Test 2: Character swap section with count.
		WantSub: fmt.Sprintf("## Character swaps (%d)", len(def.CharReplace)),
	}, { // Test 3: Buzzword section with count.
		WantSub: fmt.Sprintf("## Buzzwords (%d)", len(def.BlockWords)),
	}, { // Test 4: Phrases render without their trailing space.
		WantSub: "| `in summary,` | dropped |",
	}, { // Test 5: Table pipes inside patterns are escaped.
		WantSub: `(thing\|kicker\|deal\|catch\|secret\|problem)`,
	}, { // Test 6: Every built-in preset gets a section.
		WantSub: "### cleaver",
	}, { // Test 7: Buzzwords are inline code so the page passes its own check.
		WantSub: "`robust`",
	}}
	for testNum, test := range tests {
		t.Run(fmt.Sprintf("test %d", testNum), func(t *testing.T) {
			if !strings.Contains(stdout, test.WantSub) {
				t.Errorf("stdout missing %q", test.WantSub)
			}
		})
	}
	if strings.Contains(stdout, "\n## Word swaps") {
		t.Error("default profile has no word swaps, section should be absent at top level")
	}
}

// TestTellsJSON checks the JSON mode prints the resolved profile, matching what the
// web app exports as profile JSON.
func TestTellsJSON(t *testing.T) {
	stdout, _, err := runCLI(t, []string{"tells", "--json"}, "")
	if err != nil {
		t.Fatalf("err = %v, want nil", err)
	}
	var p sanitize.Profile
	if err := json.Unmarshal([]byte(stdout), &p); err != nil {
		t.Fatalf("output is not a profile: %v", err)
	}
	if len(p.BlockWords) != len(sanitize.DefaultProfile().BlockWords) {
		t.Errorf("blockWords = %d, want %d", len(p.BlockWords), len(sanitize.DefaultProfile().BlockWords))
	}
}

// TestTellsPreset checks a preset's additions show up in the resolved catalog.
func TestTellsPreset(t *testing.T) {
	stdout, _, err := runCLI(t, []string{"tells", "--preset", "cleaver"}, "")
	if err != nil {
		t.Fatalf("err = %v, want nil", err)
	}
	if !strings.Contains(stdout, "word swaps (") {
		t.Error("cleaver word swaps missing from the catalog")
	}
	if !strings.Contains(stdout, `"delve" => "dig"`) {
		t.Errorf("cleaver swap missing, stdout = %q", stdout[:200])
	}
}

// TestTellsRejectsArgs checks the command takes no file arguments.
func TestTellsRejectsArgs(t *testing.T) {
	_, _, err := runCLI(t, []string{"tells", "notes.md"}, "")
	if err == nil {
		t.Fatal("err = nil, want an argument error")
	}
}
