package cmd

import (
	"fmt"
	"io"
	"maps"
	"slices"
	"strings"

	"github.com/spf13/cobra"

	"github.com/dcadolph/slop-chop/cmd/config"
	"github.com/dcadolph/slop-chop/internal/sanitize"
)

// tellsCmd builds the tells subcommand.
func tellsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "tells",
		Short: "List every tell the current profile chops or flags.",
		Long: `tells prints the catalog behind the other commands: every character swap, stock
phrase, buzzword, and structural pattern the resolved profile acts on. With --json it
prints the resolved profile itself, and with --markdown it prints the docs page, so
the published catalog is generated from the same source the engine runs.`,
		Args: cobra.NoArgs,
		RunE: runTells,
	}
	f := cmd.Flags()
	f.AddFlag(&config.FlagProfile)
	f.AddFlag(&config.FlagDialect)
	f.AddFlag(&config.FlagPreset)
	f.AddFlag(&config.FlagJSON)
	f.AddFlag(&config.FlagPretty)
	f.AddFlag(&config.FlagMarkdown)
	return cmd
}

// runTells resolves the profile the same way check does and writes the catalog.
func runTells(cmd *cobra.Command, _ []string) error {
	_, profile, err := newSanitizer()
	if err != nil {
		return err
	}
	stdout := cmd.OutOrStdout()
	switch {
	case config.JSON():
		return writeJSON(stdout, profile, config.Pretty())
	case config.Markdown():
		return writeTellsMarkdown(stdout, profile)
	default:
		return writeTellsText(stdout, profile)
	}
}

// onOff renders a boolean profile switch for the text listing.
func onOff(v bool) string {
	if v {
		return "on"
	}
	return "off"
}

// sortedPairs returns the map's entries ordered by key, matching the order the rules
// compile in, so two runs always print the same catalog.
func sortedPairs(m map[string]string) [][2]string {
	keys := slices.Sorted(maps.Keys(m))
	out := make([][2]string, 0, len(keys))
	for _, k := range keys {
		out = append(out, [2]string{k, m[k]})
	}
	return out
}

// writeTellsText prints the catalog as a compact terminal listing.
func writeTellsText(w io.Writer, p sanitize.Profile) error {
	var b strings.Builder
	writeTextPairs(&b, "character swaps", p.CharReplace)
	writeTextPairs(&b, "stock phrases", p.PhraseReplace)
	writeTextPairs(&b, "word swaps", p.WordReplace)
	writeTextPairs(&b, "regex swaps", p.RegexReplace)
	if len(p.BlockWords) > 0 {
		words := slices.Sorted(slices.Values(p.BlockWords))
		fmt.Fprintf(&b, "buzzwords flagged (%d): %s\n", len(words), strings.Join(words, ", "))
	}
	writeTextPairs(&b, "patterns flagged", p.FlagPatterns)
	if len(p.Allow) > 0 {
		allowed := slices.Sorted(slices.Values(p.Allow))
		fmt.Fprintf(&b, "allowed (%d): %s\n", len(allowed), strings.Join(allowed, ", "))
	}
	fmt.Fprintf(&b, "semicolon split: %s\n", onOff(p.SplitSemicolons))
	fmt.Fprintf(&b, "space cleanup: %s\n", onOff(p.CollapseSpaces))
	dialect := string(p.Dialect)
	if dialect == "" {
		dialect = "off"
	}
	fmt.Fprintf(&b, "dialect: %s\n", dialect)
	_, err := io.WriteString(w, b.String())
	return err
}

// writeTextPairs prints one from => to section of the text listing, skipping empty
// sections so the default catalog stays short.
func writeTextPairs(b *strings.Builder, title string, m map[string]string) {
	if len(m) == 0 {
		return
	}
	fmt.Fprintf(b, "%s (%d):\n", title, len(m))
	for _, pair := range sortedPairs(m) {
		if pair[1] == "" {
			fmt.Fprintf(b, "  %q => (dropped)\n", pair[0])
			continue
		}
		fmt.Fprintf(b, "  %q => %q\n", pair[0], pair[1])
	}
}

// writeTellsMarkdown prints the catalog as the docs page. The page is generated from
// the same profile the engine compiles, so the two can never drift apart.
func writeTellsMarkdown(w io.Writer, p sanitize.Profile) error {
	var b strings.Builder
	b.WriteString(`<!-- Generated by "slop-chop tells --markdown". Edit the profile, not this file. -->

# The tells

AI writing gives itself away with the same characters, stock phrases, and buzzwords,
over and over. If you have wondered why ChatGPT sounds robotic, or which words and
phrases give AI writing away, this is the list. It covers every tell the default
profile acts on, generated straight from the profile the engine compiles, so what you
read here is exactly what gets chopped. Rebuild it any time with
` + "`slop-chop tells --markdown`" + `.

`)
	writeMarkdownSwaps(&b, "##", "Character swaps", "Rewritten in place. The usual suspects: the em-dash, smart quotes, the ellipsis.", p.CharReplace)
	writeMarkdownPhrases(&b, p.PhraseReplace)
	writeMarkdownSwaps(&b, "##", "Word swaps", "Whole words rewritten with the original casing kept.", p.WordReplace)
	writeMarkdownSwaps(&b, "##", "Regex swaps", "Custom patterns rewritten as written.", p.RegexReplace)
	writeMarkdownBlockWords(&b, p.BlockWords)
	writeMarkdownPatterns(&b, p.FlagPatterns)
	writeMarkdownCleanup(&b, p)
	writeMarkdownPresets(&b)
	_, err := io.WriteString(w, b.String())
	return err
}

// writeMarkdownSwaps prints one from and to table under a heading of the given level,
// skipping the section when the profile has no entries of that kind.
func writeMarkdownSwaps(b *strings.Builder, level, title, blurb string, m map[string]string) {
	if len(m) == 0 {
		return
	}
	fmt.Fprintf(b, "%s %s (%d)\n\n", level, title, len(m))
	if blurb != "" {
		fmt.Fprintf(b, "%s\n\n", blurb)
	}
	b.WriteString("| From | To |\n| ---- | -- |\n")
	for _, pair := range sortedPairs(m) {
		to := "`" + pair[1] + "`"
		if pair[1] == "" {
			to = "dropped"
		}
		fmt.Fprintf(b, "| `%s` | %s |\n", pair[0], to)
	}
	b.WriteString("\n")
}

// writeMarkdownPhrases prints the stock phrase table. Phrases are shown without their
// trailing space, which the rule keeps so a deletion leaves a clean sentence.
func writeMarkdownPhrases(b *strings.Builder, m map[string]string) {
	if len(m) == 0 {
		return
	}
	fmt.Fprintf(b, "## Stock phrases (%d)\n\n", len(m))
	b.WriteString(`Openers and filler that add words but no meaning. Each is dropped with its trailing
comma and space, and when it opened the sentence the next word gets its capital back.

| Phrase | Fate |
| ------ | ---- |
`)
	for _, pair := range sortedPairs(m) {
		fate := "dropped"
		if pair[1] != "" {
			fate = "`" + pair[1] + "`"
		}
		fmt.Fprintf(b, "| `%s` | %s |\n", strings.TrimRight(pair[0], " "), fate)
	}
	b.WriteString("\n")
}

// writeMarkdownBlockWords prints the buzzword list as inline code, since a table with
// this many one-word rows reads worse than a paragraph.
func writeMarkdownBlockWords(b *strings.Builder, words []string) {
	if len(words) == 0 {
		return
	}
	sorted := slices.Sorted(slices.Values(words))
	fmt.Fprintf(b, "## Buzzwords (%d)\n\n", len(sorted))
	b.WriteString(`Flagged wherever they appear, never rewritten, because the right replacement depends
on the sentence. The cleaver preset swaps the common ones for plain words when you want
that done for you.

`)
	quoted := make([]string, 0, len(sorted))
	for _, word := range sorted {
		quoted = append(quoted, "`"+word+"`")
	}
	b.WriteString(strings.Join(quoted, " ") + "\n\n")
}

// writeMarkdownPatterns prints the structural pattern table.
func writeMarkdownPatterns(b *strings.Builder, m map[string]string) {
	if len(m) == 0 {
		return
	}
	fmt.Fprintf(b, "## Structural patterns (%d)\n\n", len(m))
	b.WriteString(`Sentence shapes a word list cannot catch, like the setup-and-reveal cadence. Flag
only: the fix depends on the whole sentence, so it is left to you or the rewrite pass.

| Name | Pattern |
| ---- | ------- |
`)
	for _, pair := range sortedPairs(m) {
		fmt.Fprintf(b, "| `%s` | `%s` |\n", pair[0], strings.ReplaceAll(pair[1], "|", "\\|"))
	}
	b.WriteString("\n")
}

// writeMarkdownCleanup prints the always-on tidy passes and the dialect state.
func writeMarkdownCleanup(b *strings.Builder, p sanitize.Profile) {
	b.WriteString("## Cleanup passes\n\n")
	fmt.Fprintf(b, "| Pass | Default | Does |\n| ---- | ------- | ---- |\n")
	fmt.Fprintf(b, "| Semicolon split | %s | Turns `; it` into `. It` when the semicolon joins two clauses. |\n", onOff(p.SplitSemicolons))
	fmt.Fprintf(b, "| Space cleanup | %s | Collapses doubled spaces and pulls spaces off punctuation. |\n", onOff(p.CollapseSpaces))
	dialect := string(p.Dialect)
	if dialect == "" {
		dialect = "off"
	}
	fmt.Fprintf(b, "| Spelling dialect | %s | With `--dialect`, rewrites the other dialect's spellings. |\n", dialect)
	b.WriteString("\n")
}

// writeMarkdownPresets prints what each built-in preset adds on top of a profile.
func writeMarkdownPresets(b *strings.Builder) {
	names := sanitize.PresetNames()
	if len(names) == 0 {
		return
	}
	b.WriteString(`## Presets

Optional packs merged on top of your profile with ` + "`--preset`" + `. Your profile wins on
any conflict. The web app ships with the cleaver preset switched on.

`)
	for _, name := range names {
		pack, err := sanitize.ApplyPresets(sanitize.Profile{}, name)
		if err != nil {
			continue
		}
		fmt.Fprintf(b, "### %s\n\n", name)
		writeMarkdownSwaps(b, "####", "Word swaps", "", pack.WordReplace)
		writeMarkdownSwaps(b, "####", "Phrase swaps", "", pack.PhraseReplace)
		writeMarkdownSwaps(b, "####", "Character swaps", "", pack.CharReplace)
		if len(pack.BlockWords) > 0 {
			sorted := slices.Sorted(slices.Values(pack.BlockWords))
			quoted := make([]string, 0, len(sorted))
			for _, word := range sorted {
				quoted = append(quoted, "`"+word+"`")
			}
			fmt.Fprintf(b, "Adds %d buzzwords: %s\n\n", len(sorted), strings.Join(quoted, " "))
		}
		if len(pack.Allow) > 0 {
			sorted := slices.Sorted(slices.Values(pack.Allow))
			quoted := make([]string, 0, len(sorted))
			for _, word := range sorted {
				quoted = append(quoted, "`"+word+"`")
			}
			fmt.Fprintf(b, "Allows %d words: %s\n\n", len(sorted), strings.Join(quoted, " "))
		}
	}
}
